### ISSUE TITLE
Verify Tack, Jibe, and Jib/Sail controllers and add tests as needed

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/boat_controller#30]
The following controllers should be verified (by hand if necessary):
- [Tacking Controller](https://github.com/UBCSailbot/boat_controller/blob/master/python/tack_controller.py)
- [Jibe Controller](https://github.com/UBCSailbot/boat_controller/blob/master/python/jibe_only_rudder_controller.py)
- [Sail Controller](https://github.com/UBCSailbot/boat_controller/blob/master/python/sail_controller.py)
- [Jib Controller](https://github.com/UBCSailbot/boat_controller/blob/master/python/jib_controller.py)

It is essential to first understand what each controller **should** do, verify that the current tests support the input-output relationship that is expected, and add more tests if the test partition coverage is lacking.

If there are issues with any of these controllers, immediately schedule a meeting with @Tsuchijo and figure out the issue.

**Comment by Tsuchijo** [comment]
Jibe controller updated to properly take in apparent wind angles. Before the Jibe controller was assuming that the wind angle was given relative to north (absolute coordinates) while the value given would've been relative to the boat. Now the Jibe controller should work with values of wind direction relative to boat heading.

**Comment by Tsuchijo** [comment]
Changed Rudder feedback function to act as expected. Previously functtion was mistakenly normalized with the assumption that the input would be between 0 and 2 pi. Normalization has been removed and the function has been properly bound between -pi and pi such that the feedback function is symmetrc and returns proper values. Addtionally k feedback constant has been increased to 0.7 to make full use of the range of the rudders.
