### ISSUE TITLE
Quantizing the Winch Position

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/boat_controller#43]
### Purpose
Moving the winch a lot consumes far too much power. In addition, asking for specific winch positions may not be useful since we may not have the resolution that we want. Finally, the winch moves extremely slowly. This prompts the controller to quantize the winch position to mitigate the risk from all the above factors.

### Description
1. Add a quantization parameter to [heading_controller.py](https://github.com/UBCSailbot/boat_controller/blob/master/python/heading_controller.py) and store that value as a class member variable in the heading controller. This parameter must be an integer that ranges between [1,360]. Use this parameter when computing the winch position.

2. Change the `get_winch_position` function in [sail_controller.py](https://github.com/UBCSailbot/boat_controller/blob/master/python/sail_controller.py) to accept the quantization parameter. If the computed winch position falls in between two benchmarks, then the returned winch position should be the closest bench mark. Consider the figure below:

![Capture](https://user-images.githubusercontent.com/69879126/181697330-95df43e5-597a-4ff5-8663-5648dc6fbbfc.JPG)

This is an example when the quantization parameter is 4. Say if the computed winch position is 200. The returned winch position should be 180 since we are closest to 180. If the computed winch position is 330, then 360 should be returned since we are closest to 360.

3. Repeat step 2 for `get_winch_position` in [jib_controller.py](https://github.com/UBCSailbot/boat_controller/blob/master/python/jib_controller.py).

4. Add tests to confirm that the quantization functionality works.

5. Increase the winch update period.

6. Change the heading controller instance [boat_controller_node.py](https://github.com/UBCSailbot/boat_controller/blob/master/python/boat_controller_node.py) to accept a hardcoded quantization parameter of 4.

**Comment by DFriend01** [comment]
@Tsuchijo @jamenkaye 
Does the description above seem reasonable for the quantization mechanism for the winches?

**Comment by jamenkaye** [comment]
@DFriend01 In terms of the added functionality, I think this is great! And yes, I agree that a total of 5 evenly spaced winch positions is probably a good choice.

I'm a little confused about what the quantization parameter represents though. It seems like its just one less than the total number of evenly spaced winch positions? I'm confused why it would have a lower acceptable bound of 2. I would have thought that we need a minimum of 1 winch position for the code to run correctly, so then the lower bound could be 0?

**Comment by DFriend01** [comment]
@jamenkaye To be honest it's more for mathematical convenience that it is defined the way it is. If for example the quantization parameter was 1, then we have a step size of 360 / 1 = 360, and we would therefore always publish 0 unless we were exactly on 360.

The quantization parameter defines the step size. So in this case of 4, 360 / 4 = 90.

**Comment by jamenkaye** [comment]
Oh ok that makes sense, thanks for explaining! Sounds good
