### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/boat_controller#48]
Bring tests up to date with the latest sailbot-msg and local-pathfinding commits
- Removed some fields in the `/windSensor` topic: https://github.com/UBCSailbot/sailbot-msg/commit/eeef31e381021b23ea3d0446070d3cced0fde053
    - This is what is causing boat_controller tests to fail with sailbot-msg at the latest commit
- Created the `/lowWindConditions` topic: https://github.com/UBCSailbot/local-pathfinding/pull/277
    - Can create some tests for low power mode using this boolean

**Comment by DFriend01** [comment]
@patrick-5546 There is no need to make more tests for `/lowWindConditions` in our logic. We assume that the values are read in our unit tests and feed the inputs manually.
